mautic:
  image: mautic/mautic
  ports:
    - 80:80
  links:
    - mysql:mysql
mysql:
  image: mysql:5.6
  container_name: mysql
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: mautic
